# Headers section
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

# Redirects section
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

# Build section
[build]
  publish = "dist/"
  command = "yarn build"
