# Headers section
[[headers]]
  for = "/static/*"
  cache-control = "max-age=31536000"

[[headers]]
  for = "/assets/*"
  cache-control = "max-age=31536000"

# Redirects section
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
